name: PR Label Based On Lines

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr-labelling:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get number of updated lines of code
      id: pr
      uses: actions/github-script@v7
      with:
        result-encoding: string
        script: |
          const pr = context.payload.pull_request;
          const totalLines = (pr.additions || 0) + (pr.deletions || 0);
          if (totalLines <= 50) return 'small'
          if (totalLines > 200) return 'large'
          return 'medium'
    
    - name: Label PR based on lines of code
      uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: ${{ steps.pr.outputs.result }}
