name: PR Label Based On Lines

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr-labelling:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get number of updated lines of code
      id: pr
      uses: actions/github-script@v7
      with:
        script: |
          const pr = context.payload.pull_request;
          const totalLines = (pr.additions || 0) + (pr.deletions || 0);
          return { totalLines };
    
    - name: Label PR based on lines of code
      uses: actions-ecosystem/action-add-labels@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        labels: |
          ${{ steps.pr.outputs.totalLines <= 50 && 'small' }}
          ${{ steps.pr.outputs.totalLines > 50 && steps.pr.outputs.totalLines <= 200 && 'medium' }}
          ${{ steps.pr.outputs.totalLines > 200 && 'large' }}
